project:
  type: book
  output-dir: docs

book:
  title: "Water in movement"
  author: "xxxxxxxx"
  date: "2025-04-01"
  cover-image: www/capa.jpg
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true
  page-footer: 
    left: "Criado por ..."
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
  search: true
  repo-url: https://github.com/vituri/water-in-movement
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



